'use client';
import { useState } from 'react';
import type { FairValueResult } from '@/src/lib/analytics/valuation/types';
import { formatBangkokDateTime } from '@/src/lib/presentation/datetime';
import { canLoadFairValue } from './load-policy';
import { requestFairValue } from './fair-value-client';
import { fairValueUnavailableLabel, fairValueUnavailableReason } from './presentation';

export function FairValueSection({ symbol }: { symbol: string }) {
  const [data, setData] = useState<FairValueResult | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const analyze = async () => { if (!canLoadFairValue(true, true, true, loading)) return; setLoading(true); setError(null); const controller = new AbortController(); try { setData(await requestFairValue(symbol, controller.signal)); } catch (cause) { setError(cause instanceof Error ? cause.message : 'เกิดข้อผิดพลาด'); } finally { setLoading(false); } };
  return <section className="rounded-2xl border border-slate-800 bg-[#151B28] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-white">Nexora Composite Fair Value</h2><p className="mt-1 text-xs text-amber-300">Nexora model estimate — not a market quote</p></div>{!data && <button type="button" disabled={loading} onClick={() => void analyze()} className="min-h-11 rounded-lg bg-[#D4FF00] px-4 text-sm font-semibold text-black disabled:opacity-50">{loading ? 'กำลังตรวจข้อมูล…' : 'Analyze'}</button>}</div>{error && <p className="mt-4 text-sm text-red-300">เกิดข้อผิดพลาด: {error}</p>}{data?.status === 'unavailable' && <div className="mt-5 rounded-xl border border-amber-500/20 bg-amber-500/5 p-4"><p className="font-semibold text-amber-200">{fairValueUnavailableLabel(data.failureKind, 'th')}</p><p className="mt-2 text-sm text-amber-100">{fairValueUnavailableReason(data, 'th')}</p><p className="mt-3 text-xs text-slate-500">Provider: {data.provider ?? 'ไม่ทราบ'} · as of {formatBangkokDateTime(data.asOf)} · stale: {data.staleInputs.join(', ') || 'ไม่มี'}</p><p className="mt-1 text-xs text-slate-500">Methodology {data.methodologyVersion} · calculated {formatBangkokDateTime(data.calculatedAt)}</p><ul className="mt-2 list-disc pl-4 text-xs text-slate-500">{data.limitations.map((item) => <li key={item}>{item}</li>)}</ul></div>}{data?.status === 'available' && <div className="mt-5 space-y-4"><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Value label="Current Price" value={data.marketPrice.value}/><Value label="Base Range" value={`${data.fundamentalFairValue.base.low.toFixed(2)}–${data.fundamentalFairValue.base.high.toFixed(2)}`}/><Value label="Model Reliability" value={data.modelReliability.level}/><Value label="Models Used" value={String(data.modelResults.length)}/></div><div className="grid gap-3 sm:grid-cols-3"><Range label="Conservative" range={data.fundamentalFairValue.conservative}/><Range label="Base" range={data.fundamentalFairValue.base}/><Range label="Optimistic" range={data.fundamentalFairValue.optimistic}/></div><details className="rounded-lg border border-slate-700 p-3 text-sm"><summary className="cursor-pointer">ดูสมมติฐาน</summary><pre className="mt-2 overflow-auto text-xs text-slate-400">{JSON.stringify(data.assumptions, null, 2)}</pre></details><details className="rounded-lg border border-slate-700 p-3 text-sm"><summary className="cursor-pointer">ดูการวิเคราะห์</summary><p className="mt-2 text-slate-400">Classification: {data.companyClassification.classification.join(', ')}</p><p className="text-slate-400">Fundamental Quality: {data.fundamentalQuality.score.toFixed(1)}/100</p><p className="text-slate-400">Technical Market Context แยกจาก intrinsic value และไม่เปลี่ยน Fair Value</p></details></div>}</section>;
}
function Value({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-slate-800 p-3"><p className="text-[10px] uppercase text-slate-500">{label}</p><p className="mt-2 font-mono text-white">{value}</p></div>; }
function Range({ label, range }: { label: string; range: { low: number; high: number } }) { return <div className="rounded-lg border border-slate-800 p-3"><p className="text-xs text-slate-500">{label}</p><p className="font-mono text-white">{range.low.toFixed(2)}–{range.high.toFixed(2)}</p></div>; }
